name: Imagery
author: by Roman BÃ¶gli
icon: ðŸ“¸

frame_padding: 1px

column: 3
column_gap: 20px
row_gap: 20px

small_screen:
  column: 2
  column_gap: 10px
  row_gap: 10px

process:
  keep_order: True
  album:
    sort_by_time: True # False: sort by filename
    order_by: modify # access, modify
    reverse: False
  photo:
    sort_by_time: False
    order_by: modify
    reverse: False
    min_width: 600
    watermark:
      thumbnail: False
      original: False
      fontsize: 40
      fontfamily: Eczar-Medium.ttf
      rotate: 0

instagram: 

sass:
  sass_dir: _sass
  style: compressed
